#!/usr/bin/env node
/**
 * build-review.mjs — generate content/pilot-review.md, a human-readable dump of
 * the pilot rounds for the user's quality approval. Reads content/rounds/*.json,
 * runs validate.mjs to embed a live pass report, and flags the verbal items that
 * have no deterministic solver (needs-human-check). Regenerate anytime:
 *   node build-review.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROUNDS_DIR = path.join(HERE, "rounds");
const OUT = path.join(HERE, "pilot-review.md");

const POLY_NAME = { 3: "triangle", 4: "square", 5: "pentagon", 6: "hexagon", 7: "heptagon", 8: "octagon", circle: "circle" };
const POS_NAME = { tl: "top-left", tr: "top-right", br: "bottom-right", bl: "bottom-left", center: "center" };
const HUMAN_TIERS = ["ODD ONE OUT", "VERBAL ANALOGY", "SENTENCE COMPLETION"];
const needsHuman = (q) => q.kind === "text" && HUMAN_TIERS.includes(q.tier.toUpperCase());

const optText = (q, o) => {
  if (q.kind === "shaded") return `${o.filled ? "filled" : "empty"} ${o.shape}`;
  if (q.kind === "polygon") return o.poly === "circle" ? "circle" : `${POLY_NAME[o.poly]} (${o.poly} sides)`;
  if (q.kind === "dot") return POS_NAME[o.pos];
  return o.text;
};

function promptLine(q) {
  const base = (q.question || q.prompt || "").replace(/\n/g, " / ");
  if (q.kind === "numseries") return `${base}  —  sequence: ${q.seq.join(", ")}`;
  if (q.kind === "shaded") return `${base}  —  empty ${q.leftShape} : filled ${q.leftShape}  =  empty ${q.rightShape} : ?`;
  if (q.kind === "polygon") return `${base}  —  sides: ${q.seq.join(", ")}, ?`;
  if (q.kind === "dot") return `${base}  —  path: ${q.seq.map((p) => POS_NAME[p]).join(", ")}, ?`;
  return base;
}

const rounds = fs
  .readdirSync(ROUNDS_DIR)
  .filter((f) => /^round-\d{3}\.json$/.test(f))
  .sort()
  .map((f) => JSON.parse(fs.readFileSync(path.join(ROUNDS_DIR, f), "utf8")));

let report = "";
try {
  report = execSync("node validate.mjs --all", { cwd: HERE, encoding: "utf8" });
} catch (e) {
  report = (e.stdout || "") + (e.stderr || "");
}

const bank = JSON.parse(fs.readFileSync(path.join(HERE, "master-question-bank.json"), "utf8"));

let md = "";
const w = (s = "") => (md += s + "\n");

w("# Pilot Review — Rounds 1 to 5 (Smart Fella or Fart Smella)");
w();
w("> Generated by `content/build-review.mjs`. This is the quality-approval artifact for the pilot:");
w("> every question in the 5 pilot rounds, with its correct answer + explanation, plus the live");
w("> validator report and the verbal items that need a human eye (no deterministic solver exists).");
w("> Nothing here is rendered yet. Approve the quality bar, then we render + scale to ~100 rounds.");
w();

// ---- overview ----
w("## Overview");
w();
w("| Round | Title | Battery mix | Difficulty | Answer letters | Needs human check |");
w("|---|---|---|---|---|---|");
for (const r of rounds) {
  const c = { verbal: 0, quantitative: 0, nonverbal: 0 };
  const d = { easy: 0, medium: 0, hard: 0 };
  const L = { A: 0, B: 0, C: 0, D: 0 };
  let hc = 0;
  for (const q of r.questions) {
    c[q.category]++;
    d[q.difficulty]++;
    L[q.ansLetter]++;
    if (needsHuman(q)) hc++;
  }
  w(`| ${r.slug} | ${r.title} | V${c.verbal}/Q${c.quantitative}/N${c.nonverbal} | E${d.easy}/M${d.medium}/H${d.hard} | A${L.A} B${L.B} C${L.C} D${L.D} | ${hc} |`);
}
w();
w(`**Master question bank:** ${bank.count} entries (all ${rounds.length} pilot rounds appended; every question globally unique by signature).`);
w();

// ---- validator report ----
w("## Validator report (live)");
w();
w("```");
w(report.trim());
w("```");
w();

// ---- needs-human-check summary ----
w("## Items flagged `needs-human-check` (verbal — no deterministic solver)");
w();
w("These are the verbal items (odd-one-out, verbal analogy, sentence completion). The validator");
w("confirms they are structurally sound (one marked answer, no duplicate/near-duplicate, no dashes),");
w("but a human should confirm the answer is unambiguous and kid-appropriate.");
w();
w("| Round | Q | Tier | Prompt | Answer |");
w("|---|---|---|---|---|");
for (const r of rounds) {
  for (const q of r.questions) {
    if (!needsHuman(q)) continue;
    w(`| ${r.round} | ${q.id} | ${q.tier} | ${promptLine(q).replace(/\|/g, "/")} | ${q.ansLabel} |`);
  }
}
w();

// ---- per-round full dump ----
for (const r of rounds) {
  w(`## ${r.title}`);
  w();
  w(`\`${r.slug}\` · Grade ${r.grade} / CogAT Level ${r.cogatLevel} · 15 questions`);
  w();
  for (const q of r.questions) {
    const flag = needsHuman(q) ? " _(needs-human-check)_" : "";
    w(`**Q${q.id} · ${q.tier}** · ${q.category} · ${q.difficulty} · ${q.countdown}s${flag}`);
    w();
    w(`- Prompt: ${promptLine(q)}`);
    for (const o of q.options) {
      const mark = o.letter === q.ansLetter ? " ✅" : "";
      w(`  - ${o.letter}) ${optText(q, o)}${mark}`);
    }
    w(`- Correct: ${q.ansLetter} · ${q.ansLabel}`);
    w(`- Explanation: ${q.explanation}`);
    w();
  }
}

fs.writeFileSync(OUT, md);
console.log(`wrote ${OUT} (${rounds.length} rounds, ${rounds.reduce((n, r) => n + r.questions.length, 0)} questions)`);
