/**
 * verbal-bank.mjs — curated Grade-5 verbal items for the mass-gen generator.
 *
 * Each item has a SINGLE unambiguous correct answer by construction (clean
 * category outliers, one-relation analogies, strong context-clue sentences) and
 * contains NO em/en dashes. `correct` is the right answer; `distractors` are the
 * three wrong options. gen-rounds.mjs shuffles them into A..D and balances the
 * answer-letter distribution. The AI-judge pass (CONTENT_PIPELINE.md) is the
 * safety net that re-checks single-answer-ness on top of this curation.
 *
 * ODD ONE OUT: `correct` is the odd item; `distractors` are the three that belong.
 */
const ODD_Q = "WHICH ONE DOES NOT BELONG?";
const odd = (correct, distractors, explanation) => ({ q: ODD_Q, correct, distractors, explanation });
const ana = (a, b, c, correct, distractors, explanation) => ({ q: `${a} IS TO ${b} AS\n${c} IS TO ?`, correct, distractors, explanation });
const sen = (q, correct, distractors, explanation, fontSize = 56) => ({ q, correct, distractors, explanation, fontSize });

export const VERBAL = {
  oddoneout: [
    odd("POTATO", ["PEACH", "PEAR", "PLUM"], "A peach, pear, and plum are all fruits. A potato is a vegetable, so it does not belong."),
    odd("EAGLE", ["LION", "TIGER", "WOLF"], "A lion, tiger, and wolf are mammals. An eagle is a bird, so it does not belong."),
    odd("OAK", ["ROSE", "TULIP", "DAISY"], "A rose, tulip, and daisy are flowers. An oak is a tree, so it does not belong."),
    odd("BOAT", ["CAR", "BUS", "TRUCK"], "A car, bus, and truck travel on roads. A boat travels on water, so it does not belong."),
    odd("SHARK", ["ROBIN", "SPARROW", "OWL"], "A robin, sparrow, and owl are birds. A shark is a fish, so it does not belong."),
    odd("SNAKE", ["DOG", "CAT", "HORSE"], "A dog, cat, and horse have four legs and fur. A snake does not, so it does not belong."),
    odd("THREE", ["RED", "BLUE", "GREEN"], "Red, blue, and green are colors. Three is a number, so it does not belong."),
    odd("CIRCLE", ["RED", "YELLOW", "PURPLE"], "Red, yellow, and purple are colors. A circle is a shape, so it does not belong."),
    odd("CHAIR", ["ARM", "LEG", "HAND"], "An arm, leg, and hand are body parts. A chair is furniture, so it does not belong."),
    odd("WOOD", ["GOLD", "SILVER", "IRON"], "Gold, silver, and iron are metals. Wood is not a metal, so it does not belong."),
    odd("SUN", ["MARS", "VENUS", "JUPITER"], "Mars, Venus, and Jupiter are planets. The sun is a star, so it does not belong."),
    odd("WHALE", ["ANT", "BEE", "BEETLE"], "An ant, bee, and beetle are insects. A whale is a mammal, so it does not belong."),
    odd("APPLE", ["CARROT", "CELERY", "SPINACH"], "Carrot, celery, and spinach are vegetables. An apple is a fruit, so it does not belong."),
    odd("SPOON", ["SHIRT", "PANTS", "JACKET"], "A shirt, pants, and jacket are clothing. A spoon is not, so it does not belong."),
    odd("RAIN", ["CHAIR", "TABLE", "BED"], "A chair, table, and bed are furniture. Rain is weather, so it does not belong."),
    odd("PIANO", ["APPLE", "ORANGE", "MANGO"], "An apple, orange, and mango are fruits. A piano is an instrument, so it does not belong."),
    odd("TROUT", ["COW", "GOAT", "SHEEP"], "A cow, goat, and sheep are farm mammals. A trout is a fish, so it does not belong."),
    odd("GLASS", ["HAMMER", "SAW", "WRENCH"], "A hammer, saw, and wrench are tools. Glass is a material, so it does not belong."),
    odd("SQUARE", ["ONE", "FIVE", "NINE"], "One, five, and nine are numbers. A square is a shape, so it does not belong."),
    odd("BANANA", ["SOCCER", "TENNIS", "HOCKEY"], "Soccer, tennis, and hockey are sports. A banana is a fruit, so it does not belong."),
    odd("DESK", ["LION", "ZEBRA", "GIRAFFE"], "A lion, zebra, and giraffe are animals. A desk is furniture, so it does not belong."),
    odd("SEVEN", ["TRIANGLE", "CIRCLE", "SQUARE"], "A triangle, circle, and square are shapes. Seven is a number, so it does not belong."),
    odd("CLOUD", ["OAK", "PINE", "MAPLE"], "An oak, pine, and maple are trees. A cloud is in the sky, so it does not belong."),
    odd("BRICK", ["DOG", "RABBIT", "MOUSE"], "A dog, rabbit, and mouse are animals. A brick is not alive, so it does not belong."),
    odd("ROSE", ["CAR", "TRAIN", "PLANE"], "A car, train, and plane carry people. A rose is a flower, so it does not belong."),
    odd("MILK", ["HAMMER", "DRILL", "SAW"], "A hammer, drill, and saw are tools. Milk is a drink, so it does not belong."),
    odd("PENCIL", ["DOG", "CAT", "COW"], "A dog, cat, and cow are animals. A pencil is not alive, so it does not belong."),
    odd("LION", ["APPLE", "GRAPE", "LEMON"], "An apple, grape, and lemon are fruits. A lion is an animal, so it does not belong."),
    odd("RIVER", ["SHIRT", "DRESS", "COAT"], "A shirt, dress, and coat are clothing. A river is water, so it does not belong."),
    odd("STONE", ["SPARROW", "HAWK", "CROW"], "A sparrow, hawk, and crow are birds. A stone is not alive, so it does not belong."),
    odd("DRUM", ["MERCURY", "SATURN", "NEPTUNE"], "Mercury, Saturn, and Neptune are planets. A drum is an instrument, so it does not belong."),
    odd("BOOK", ["ROSE", "LILY", "TULIP"], "A rose, lily, and tulip are flowers. A book is not a flower, so it does not belong."),
  ],

  analogy: [
    ana("BIG", "SMALL", "TALL", "SHORT", ["WIDE", "LONG", "HIGH"], "Big and small are opposites, so the opposite of tall is short."),
    ana("UP", "DOWN", "LEFT", "RIGHT", ["TURN", "SIDE", "BACK"], "Up and down are opposites, so the opposite of left is right."),
    ana("FAST", "SLOW", "EARLY", "LATE", ["QUICK", "SOON", "TIME"], "Fast and slow are opposites, so the opposite of early is late."),
    ana("HAPPY", "SAD", "LOUD", "QUIET", ["NOISE", "ANGRY", "BIG"], "Happy and sad are opposites, so the opposite of loud is quiet."),
    ana("OPEN", "CLOSED", "PUSH", "PULL", ["DOOR", "OPEN", "SHUT"], "Open and closed are opposites, so the opposite of push is pull."),
    ana("WET", "DRY", "FULL", "EMPTY", ["WATER", "FULL", "HALF"], "Wet and dry are opposites, so the opposite of full is empty."),
    ana("HARD", "SOFT", "HEAVY", "LIGHT", ["BIG", "STRONG", "ROCK"], "Hard and soft are opposites, so the opposite of heavy is light."),
    ana("RICH", "POOR", "WIN", "LOSE", ["GAME", "PLAY", "SCORE"], "Rich and poor are opposites, so the opposite of win is lose."),
    ana("BEGIN", "END", "FIRST", "LAST", ["NEXT", "ONE", "FRONT"], "Begin and end are opposites, so the opposite of first is last."),
    ana("NEAR", "FAR", "HIGH", "LOW", ["TALL", "UP", "SKY"], "Near and far are opposites, so the opposite of high is low."),
    ana("BUY", "SELL", "GIVE", "TAKE", ["GIFT", "HAND", "KEEP"], "Buy and sell are opposites, so the opposite of give is take."),
    ana("DAY", "NIGHT", "SUMMER", "WINTER", ["SPRING", "SUN", "WARM"], "Day and night are opposites, so the opposite of summer is winter."),
    ana("DOG", "KENNEL", "HORSE", "STABLE", ["SADDLE", "FARM", "HAY"], "A dog lives in a kennel, so a horse lives in a stable."),
    ana("PIG", "PEN", "DOG", "KENNEL", ["BONE", "BARK", "LEASH"], "A pig lives in a pen, so a dog lives in a kennel."),
    ana("HORSE", "STABLE", "RABBIT", "BURROW", ["CARROT", "HOP", "EAR"], "A horse lives in a stable, so a rabbit lives in a burrow."),
    ana("CAT", "KITTEN", "DOG", "PUPPY", ["BONE", "BARK", "TAIL"], "A baby cat is a kitten, so a baby dog is a puppy."),
    ana("COW", "CALF", "HORSE", "FOAL", ["HAY", "RUN", "MANE"], "A baby cow is a calf, so a baby horse is a foal."),
    ana("SHEEP", "LAMB", "FROG", "TADPOLE", ["POND", "JUMP", "GREEN"], "A baby sheep is a lamb, so a baby frog is a tadpole."),
    ana("BEAR", "CUB", "HEN", "CHICK", ["EGG", "FARM", "WING"], "A baby bear is a cub, so a baby hen is a chick."),
    ana("LION", "CUB", "SHEEP", "LAMB", ["WOOL", "FARM", "BAA"], "A baby lion is a cub, so a baby sheep is a lamb."),
    ana("DOG", "BARK", "CAT", "MEOW", ["PURR", "TAIL", "PAW"], "A dog says bark, so a cat says meow."),
    ana("COW", "MOO", "DUCK", "QUACK", ["POND", "SWIM", "WING"], "A cow says moo, so a duck says quack."),
    ana("LION", "ROAR", "SNAKE", "HISS", ["BITE", "SLITHER", "SCALE"], "A lion says roar, so a snake says hiss."),
    ana("HORSE", "NEIGH", "SHEEP", "BAA", ["WOOL", "FARM", "GRASS"], "A horse says neigh, so a sheep says baa."),
    ana("BEE", "BUZZ", "WOLF", "HOWL", ["FUR", "PACK", "MOON"], "A bee says buzz, so a wolf says howl."),
    ana("PAINTER", "BRUSH", "FARMER", "PLOW", ["FIELD", "CROP", "BARN"], "A painter uses a brush, so a farmer uses a plow."),
    ana("WRITER", "PEN", "CHEF", "KNIFE", ["FOOD", "PLATE", "OVEN"], "A writer uses a pen, so a chef uses a knife."),
    ana("TEACHER", "CHALK", "GARDENER", "SPADE", ["PLANT", "SOIL", "SEED"], "A teacher uses chalk, so a gardener uses a spade."),
    ana("CARPENTER", "HAMMER", "TAILOR", "NEEDLE", ["CLOTH", "THREAD", "SHIRT"], "A carpenter uses a hammer, so a tailor uses a needle."),
    ana("WINDOW", "GLASS", "BOOK", "PAPER", ["WORD", "READ", "COVER"], "A window is made of glass, so a book is made of paper."),
    ana("TIRE", "RUBBER", "RING", "GOLD", ["FINGER", "SHINY", "ROUND"], "A tire is made of rubber, so a ring is made of gold."),
    ana("SPOON", "METAL", "CANDLE", "WAX", ["FLAME", "LIGHT", "MELT"], "A spoon is made of metal, so a candle is made of wax."),
    ana("TABLE", "WOOD", "BOTTLE", "PLASTIC", ["WATER", "CAP", "DRINK"], "A table is made of wood, so a bottle is made of plastic."),
    ana("FINGER", "HAND", "TOE", "FOOT", ["LEG", "NAIL", "SHOE"], "A finger is part of a hand, so a toe is part of a foot."),
    ana("PETAL", "FLOWER", "PAGE", "BOOK", ["WORD", "READ", "STORY"], "A petal is part of a flower, so a page is part of a book."),
    ana("WHEEL", "CAR", "SAIL", "BOAT", ["WATER", "WIND", "ROPE"], "A wheel is part of a car, so a sail is part of a boat."),
    ana("TEACHER", "SCHOOL", "DOCTOR", "HOSPITAL", ["NURSE", "SICK", "MEDICINE"], "A teacher works in a school, so a doctor works in a hospital."),
    ana("CHEF", "KITCHEN", "JUDGE", "COURT", ["LAW", "JAIL", "RULE"], "A chef works in a kitchen, so a judge works in a court."),
    ana("PILOT", "AIRPLANE", "SAILOR", "SHIP", ["SEA", "WAVE", "ANCHOR"], "A pilot works on an airplane, so a sailor works on a ship."),
    ana("ACTOR", "STAGE", "BAKER", "BAKERY", ["BREAD", "CAKE", "OVEN"], "An actor works on a stage, so a baker works in a bakery."),
    ana("KNIFE", "CUT", "BROOM", "SWEEP", ["CLEAN", "FLOOR", "DUST"], "A knife is used to cut, so a broom is used to sweep."),
    ana("EYE", "SEE", "EAR", "HEAR", ["SOUND", "LISTEN", "NOSE"], "An eye is used to see, so an ear is used to hear."),
    ana("LAMP", "LIGHT", "OVEN", "HEAT", ["COOK", "FOOD", "HOT"], "A lamp gives light, so an oven gives heat."),
    ana("PEN", "WRITE", "SCISSORS", "CUT", ["PAPER", "SHARP", "SNIP"], "A pen is used to write, so scissors are used to cut."),
    ana("BIRD", "FLY", "FISH", "SWIM", ["WATER", "FIN", "JUMP"], "A bird moves by flying, so a fish moves by swimming."),
    ana("SNOW", "COLD", "FIRE", "HOT", ["BURN", "RED", "SMOKE"], "Snow is cold, so fire is hot."),
    ana("LEMON", "SOUR", "SUGAR", "SWEET", ["WHITE", "CANDY", "SALT"], "A lemon tastes sour, so sugar tastes sweet."),
    ana("KING", "CROWN", "SOLDIER", "HELMET", ["SWORD", "ARMY", "BOOT"], "A king wears a crown, so a soldier wears a helmet."),
  ],

  sentence: [
    sen("BECAUSE IT WAS RAINING HARD, MAYA OPENED\nHER ______ TO STAY DRY ON THE WALK HOME.", "UMBRELLA", ["BOOK", "WINDOW", "LAMP"], "You open an umbrella to stay dry in the rain, so umbrella is the answer."),
    sen("THE SOUP WAS FAR TOO ______ TO EAT, SO WE\nWAITED FOR IT TO COOL DOWN FIRST.", "HOT", ["COLD", "SWEET", "EMPTY"], "Waiting for it to cool means it was hot, so hot is the answer."),
    sen("AFTER RUNNING THE WHOLE RACE, THE RUNNER\nFELT VERY ______ AND SAT DOWN TO REST.", "TIRED", ["HAPPY", "FAST", "EARLY"], "Needing to rest after a race means the runner was tired."),
    sen("SINCE THE ROOM WAS COMPLETELY ______, WE\nTURNED ON A LAMP SO WE COULD SEE.", "DARK", ["BRIGHT", "WARM", "LARGE"], "You turn on a lamp when a room is dark, so dark is the answer."),
    sen("WE COULD NOT HEAR THE TEACHER AT ALL\nBECAUSE THE ROOM WAS FAR TOO ______.", "NOISY", ["QUIET", "EMPTY", "CLEAN"], "Not being able to hear means the room was noisy."),
    sen("THE ICE CREAM STARTED TO ______ QUICKLY\nBECAUSE THE SUMMER DAY WAS SO HOT.", "MELT", ["FREEZE", "GROW", "SHINE"], "Ice cream melts when it gets hot, so melt is the answer."),
    sen("MY BROTHER WAS ______ WHEN HE OPENED HIS\nGIFT AND SAW THE SHINY NEW BIKE.", "EXCITED", ["BORED", "SLEEPY", "HUNGRY"], "Getting a wanted gift makes you excited, so excited is the answer."),
    sen("THE OLD BRIDGE WAS NOT SAFE, SO THE CITY\nDECIDED TO ______ A BRAND NEW ONE.", "BUILD", ["BREAK", "PAINT", "CLIMB"], "You build a new bridge to replace an unsafe one, so build is the answer."),
    sen("PLEASE BE ______ WITH THE GLASS VASE SO\nTHAT IT DOES NOT FALL AND BREAK.", "CAREFUL", ["QUICK", "LOUD", "SILLY"], "You must be careful so a glass vase does not break."),
    sen("THE GARDEN WAS FULL OF ______ FLOWERS IN\nRED, YELLOW, AND PURPLE.", "COLORFUL", ["PLAIN", "EMPTY", "TINY"], "Many different colors means the flowers were colorful."),
    sen("BECAUSE SHE PRACTICED EVERY SINGLE DAY,\nLILA BECAME A VERY ______ PIANO PLAYER.", "SKILLED", ["LAZY", "SLEEPY", "HUNGRY"], "Practicing every day makes you skilled, so skilled is the answer."),
    sen("THE DESERT GETS ALMOST NO RAIN, SO THE\nGROUND THERE IS USUALLY VERY ______.", "DRY", ["WET", "GREEN", "COLD"], "With almost no rain, the ground is dry."),
    sen("THE BABY WAS SLEEPING, SO WE ALL TRIED TO\nSTAY ______ AND NOT WAKE HER UP.", "QUIET", ["LOUD", "BUSY", "AWAKE"], "You stay quiet so you do not wake a sleeping baby."),
    sen("THE HEAVY BOX WAS HARD TO ______, SO TWO\nPEOPLE CARRIED IT TOGETHER.", "LIFT", ["DROP", "OPEN", "PAINT"], "A heavy box is hard to lift, so lift is the answer."),
    sen("THE STORY WAS SO ______ THAT I COULD NOT\nSTOP TURNING THE PAGES.", "INTERESTING", ["BORING", "SHORT", "QUIET"], "Not wanting to stop reading means the story was interesting."),
    sen("THE PLANT ON THE WINDOWSILL GREW TALL\nBECAUSE IT GOT PLENTY OF ______ AND WATER.", "SUNLIGHT", ["DARKNESS", "NOISE", "PAPER"], "Plants need sunlight and water to grow, so sunlight is the answer."),
    sen("HE COULD NOT FIND HIS KEYS BECAUSE HIS\nWHOLE ROOM WAS SO ______ AND CLUTTERED.", "MESSY", ["CLEAN", "EMPTY", "BRIGHT"], "Cluttered and hard to search means the room was messy."),
    sen("THE CAKE TASTED VERY ______ BECAUSE MY\nAUNT ADDED LOTS OF SUGAR.", "SWEET", ["SALTY", "SOUR", "BITTER"], "Lots of sugar makes a cake taste sweet."),
    sen("THE MARATHON WAS A LONG AND ______ RACE\nTHAT TOOK MANY HOURS TO FINISH.", "DIFFICULT", ["EASY", "SHORT", "SILLY"], "A long race that takes hours is difficult, so difficult is the answer."),
    sen("WE WORE THICK COATS AND GLOVES BECAUSE\nTHE WINTER MORNING WAS SO ______.", "COLD", ["HOT", "SUNNY", "LOUD"], "You wear coats and gloves when it is cold."),
    sen("THE TWO TEAMS WERE ______ , SO THE GAME\nENDED WITH THE SAME SCORE FOR BOTH.", "TIED", ["WINNING", "LOSING", "READY"], "The same score for both teams means the game was tied."),
    sen("SHE SPOKE IN A ______ VOICE SO THAT ONLY\nHER FRIEND NEXT TO HER COULD HEAR.", "SOFT", ["LOUD", "ANGRY", "HAPPY"], "Speaking so only one person hears means a soft voice."),
  ],
};
