#!/usr/bin/env python3
"""
Render the Gemini-voiced master quiz video -- Round 02, "CogAT Style".

Reuses the established Round-01 pipeline verbatim:
  - on-brand Pillow plates from render_demo_quiz.py (Anton + DM Sans, thick black
    borders, hard ZERO-blur offset shadows, rotating color blocks, mint checks),
    rendered with supersampled anti-aliasing (QUIZ_SS, default 4 here),
  - narration generated by Gemini TTS (gemini-2.5-pro-preview-tts, voice "Puck")
    via the TrueFoundry gateway (see gen_vo.sh; API key never printed),
  - a light tick bed under each countdown + a soft ding under each reveal,
  - a ducked music arc (Game Show Fanfare -> Prize Wheel Parade bed -> Winner
    Spin) sidechained under the VO, then an HQ libx264 crf16/slow encode.

Content is 5 ORIGINAL CogAT-STYLE reasoning items (video/content/cogat-style-
round.md): Q1 verbal analogy, Q2 verbal classification, Q3 number series,
Q4 number analogy, Q5 nonverbal rotation (drawn as arrow icons). Parent-email
gate only; no child PII; no Alpha branding.

Steps (run in order):
  render_cogat_round.py frames   # draw all PNGs / countdown frame sequences (SSAA)
  render_cogat_round.py bodies   # write Gemini TTS request bodies (no API key)
  # ...then generate the wavs:  VO_BODIES=/tmp/cogat_vo/bodies VO_OUT=/tmp/cogat_vo bash gen_vo.sh
  render_cogat_round.py build    # size to VO, per-seg HQ clips, concat -> A/V master
  render_cogat_round.py music    # build ducked music bed, mux, verify, sample frames
"""
import contextlib
import json
import os
import re
import subprocess
import sys
import wave

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
os.environ.setdefault("QUIZ_SS", "4")  # crisp supersampled anti-aliasing
import render_demo_quiz as R  # noqa: E402  (brand plate drawing + palette)

FF = "/opt/homebrew/bin/ffmpeg"
FP = "/opt/homebrew/bin/ffprobe"
ROOT = "/Users/khoilam/Documents/Crossover/30mpc-website-design-cursor"

WORK = "/tmp/cogat"
FRAMES = f"{WORK}/frames"
CLIPS = f"{WORK}/clips"
VO = "/tmp/cogat_vo"
BODIES = f"{VO}/bodies"
META = f"{WORK}/meta.json"
CONCAT_AV = f"{WORK}/round-02-concat.mp4"   # HQ video + VO/SFX audio
OUT = f"{ROOT}/video/renders/round-02-cogat-master.mp4"

# The user's music assets -- read IN PLACE, never moved/altered.
MUSIC_DIR = "/Users/khoilam/Documents/Crossover/Smart Fella Video Campaign/Audio Assets/Music"
FANFARE = f"{MUSIC_DIR}/Game Show Fanfare.mp3"
PARADE = f"{MUSIC_DIR}/Prize Wheel Parade (1).mp3"
WINNER = f"{MUSIC_DIR}/Winner Spin.mp3"

MODEL = "gemini-2.5-pro-preview-tts"
VOICE = "Puck"  # upbeat Gemini prebuilt voice -> game-show host energy

# Natural-language style directives. Gemini TTS interprets (does NOT speak) the
# text before the colon (verified in Round 01: prefixed vs plain = same spoken
# length, different prosody).
HOST = "Read this like a high-energy, upbeat TV game-show host, fast and punchy"
REVEAL = "Read this like a game-show host cheerfully revealing the answer"
URGENT = "Shout this with urgent, excited game-show energy"
WARM = "Read this warmly and invitingly, like a friendly game-show host"

# key -> (style, spoken line). Fresh, original narration for the CogAT round.
NARR = {
    "intro": (HOST,
              "Welcome back to the Brain Teaser Quiz! Round two, and today we're "
              "putting that big, beautiful brain to the test with five brand-new "
              "mind-benders. Words, numbers, and a twisty picture puzzle. Ready? "
              "Let's play!"),
    "q1": (HOST,
           "Question one, a word puzzle. Ocean is to puddle, as mountain is "
           "to... what? Is it A, valley... B, hill... C, river... or D, rock? "
           "Six seconds, go!"),
    "q2": (HOST,
           "Question two! One of these does not belong. Robin... sparrow... "
           "salmon... eagle. Which is the odd one out, A, B, C, or D? Five "
           "seconds!"),
    "q3": (HOST,
           "Question three, a number series. Two, six, twelve, twenty, thirty, "
           "and then... what comes next? A, thirty-six... B, forty... C, "
           "forty-two... or D, forty-four? Seven seconds on the clock!"),
    "q4": (HOST,
           "Question four, a number analogy. Two makes four, three makes nine, "
           "four makes sixteen, so five makes... what? A, ten... B, twenty... "
           "C, twenty-five... or D, thirty-two? Six seconds!"),
    "q5": (HOST,
           "Last one, a picture puzzle! Watch the arrow. It points up, then "
           "right, then down. Which way does it point next? A, left... B, up... "
           "C, right... or D, down? Six seconds!"),
    "timesup": (URGENT, "Time's up! Pencils down!"),
    "r1": (REVEAL,
           "The answer is B, hill! An ocean shrinks down to a puddle, so a "
           "mountain shrinks down to a hill. Same thing, tiny version!"),
    "r2": (REVEAL,
           "It's C, salmon! A robin, a sparrow, and an eagle are all birds. But "
           "a salmon? That's a fish!"),
    "r3": (REVEAL,
           "The answer is C, forty-two! Look at the jumps: plus four, plus six, "
           "plus eight, plus ten. The next jump is plus twelve, and thirty plus "
           "twelve is forty-two!"),
    "r4": (REVEAL,
           "It's C, twenty-five! Every number is multiplied by itself. Two times "
           "two is four, three times three is nine, and five times five is "
           "twenty-five!"),
    "r5": (REVEAL,
           "The answer is A, left! The arrow spins a quarter-turn clockwise "
           "every time: up, right, down... and next comes left!"),
    "score": (HOST,
              "So, how did you do? Five out of five, you are a certified smart "
              "fella! Three or four, one sharp cookie. Two or fewer? Hey, every "
              "rookie riddler starts somewhere!"),
    "outro": (WARM,
              "Want to see your full results and how you stack up? Ask a parent "
              "or guardian to enter their email on screen. There are five "
              "hundred and two thousand dollar prizes for parents up for grabs. "
              "Check the official rules, and we'll see you in round three!"),
}

# ---- the 5 CogAT-style questions (see video/content/cogat-style-round.md) ----
TOTAL_Q = 5
QUESTIONS = [
    dict(idx=1, kind="text", bg=R.BLUE, tier="VERBAL ANALOGY", tier_color=R.MINT,
         question="OCEAN IS TO PUDDLE AS\nMOUNTAIN IS TO ?",
         options=[("A", "VALLEY"), ("B", "HILL"), ("C", "RIVER"), ("D", "ROCK")],
         countdown=6, cd_accent=R.YELLOW, bar_accent=R.YELLOW,
         ans="B", ans_label="HILL",
         expl="An ocean shrinks to a puddle, so a mountain shrinks to a hill - "
              "the tiny version of the same thing."),
    dict(idx=2, kind="text", bg=R.CORAL, tier="ODD ONE OUT", tier_color=R.MINT,
         question="WHICH ONE DOES NOT BELONG?",
         options=[("A", "ROBIN"), ("B", "SPARROW"), ("C", "SALMON"), ("D", "EAGLE")],
         countdown=5, cd_accent=R.YELLOW, bar_accent=R.YELLOW,
         ans="C", ans_label="SALMON",
         expl="A robin, sparrow, and eagle are all birds. A salmon is a fish, so "
              "it doesn't belong."),
    dict(idx=3, kind="text", bg=R.YELLOW, tier="NUMBER SERIES", tier_color=R.CORAL,
         question="WHAT COMES NEXT?\n2   6   12   20   30   ?",
         options=[("A", "36"), ("B", "40"), ("C", "42"), ("D", "44")],
         countdown=7, cd_accent=R.CORAL, bar_accent=R.CORAL,
         ans="C", ans_label="42",
         expl="The gaps grow +4, +6, +8, +10, so the next gap is +12. "
              "That makes 30 + 12 = 42."),
    dict(idx=4, kind="text", bg=R.BLUE, tier="NUMBER ANALOGY", tier_color=R.YELLOW,
         question="WHICH NUMBER FITS?\n2 -> 4,   3 -> 9,   4 -> 16,   5 -> ?",
         options=[("A", "10"), ("B", "20"), ("C", "25"), ("D", "32")],
         countdown=6, cd_accent=R.YELLOW, bar_accent=R.YELLOW,
         ans="C", ans_label="25",
         expl="Each number is multiplied by itself: 2 x 2 = 4, 3 x 3 = 9, "
              "4 x 4 = 16, so 5 x 5 = 25."),
    dict(idx=5, kind="arrow", bg=R.CORAL, tier="ROTATION", tier_color=R.YELLOW,
         prompt="WHICH WAY DOES THE ARROW POINT NEXT?",
         seq=["up", "right", "down"],
         options=[("A", "left"), ("B", "up"), ("C", "right"), ("D", "down")],
         countdown=6, cd_accent=R.YELLOW, bar_accent=R.YELLOW,
         ans="A", ans_label="LEFT", ans_dir="left",
         expl="The arrow turns a quarter-turn clockwise each step: "
              "up, right, down, then left."),
]

SCORE_TIERS = [
    ("5 / 5", "CERTIFIED SMART FELLA", R.MINT),
    ("3-4", "SHARP COOKIE", R.YELLOW),
    ("0-2", "ROOKIE RIDDLER", R.CORAL),
]

# Light audio bed exprs (kept low so the VO stays on top).
TICK = "0.09*sin(2*PI*1150*t)*exp(-32*mod(t,1))"
DING = "0.16*sin(2*PI*880*t)*exp(-3.5*t)+0.10*sin(2*PI*1320*t)*exp(-3.5*t)"

LEAD = 0.35      # silence before VO on static plates
TRAIL = 0.80     # silence after VO on static plates
AR = 48000

# --- HQ deliverable encode (user spec: libx264 crf16 preset slow, yuv420p) ---
ENC_HQ = [
    "-c:v", "libx264", "-preset", "slow", "-crf", "16", "-pix_fmt", "yuv420p",
    "-r", "30", "-profile:v", "high", "-level:v", "4.2",
    "-x264-params", "keyint=60:min-keyint=60:scenecut=0",
    "-color_primaries", "bt709", "-color_trc", "bt709", "-colorspace", "bt709",
]
# Near-lossless per-segment intermediate so the single crf16 concat is the only
# meaningful compression step (no visible generation loss on the flat-color art).
ENC_INT = [
    "-c:v", "libx264", "-preset", "veryfast", "-crf", "12", "-pix_fmt", "yuv420p",
    "-r", "30", "-profile:v", "high", "-level:v", "4.2",
    "-x264-params", "keyint=60:min-keyint=60:scenecut=0",
    "-color_primaries", "bt709", "-color_trc", "bt709", "-colorspace", "bt709",
]
AENC = ["-c:a", "aac", "-b:a", "192k", "-ar", str(AR), "-ac", "2"]

# --- music mix design ---
# Per-stem shaping (fades + relative trims); absolute level is set by the
# auto-calibrated master gain so the ducked bed lands the target dB under the VO.
FADE = 1.5
XF = 1.5                 # fanfare->parade overlap
FAN_LEN = 13.0          # fanfare open length
WIN_LEN = 15.0          # winner-spin close length
STEM_VOL = {"fan": 0.0, "par": -2.5, "win": -1.0}  # parade bed sits lowest
# sidechain duck: music is compressed whenever the VO (sidechain key) is present
SC = "threshold=0.03:ratio=8:attack=20:release=320:makeup=1:detection=rms:link=average"
TARGET_SEP_DB = 12.0    # aim: music ~12 dB under the VO during narration (10-14 band)


def sh(cmd):
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode != 0:
        sys.stderr.write("CMD FAILED: " + " ".join(map(str, cmd)) + "\n" + p.stderr + "\n")
        raise SystemExit(1)
    return p


def wav_dur(path):
    with contextlib.closing(wave.open(path, "rb")) as w:
        return w.getnframes() / float(w.getframerate())


# ------------------------------------------------------------------- frames
def frames():
    for d in (FRAMES, CLIPS):
        os.makedirs(d, exist_ok=True)
    import shutil

    R.render_title(f"{FRAMES}/title.png")

    for q in QUESTIONS:
        if q["kind"] == "arrow":
            cfg = dict(idx=q["idx"], total=TOTAL_Q, bg=q["bg"], tier=q["tier"],
                       tier_color=q["tier_color"], prompt=q["prompt"], seq=q["seq"],
                       options=q["options"], countdown=q["countdown"],
                       cd_accent=q["cd_accent"], bar_accent=q["bar_accent"],
                       outdir=f"{FRAMES}/q{q['idx']}")
            R.render_arrow_question(cfg)
        else:
            cfg = dict(idx=q["idx"], total=TOTAL_Q, bg=q["bg"], tier=q["tier"],
                       tier_color=q["tier_color"], question=q["question"],
                       options=q["options"], countdown=q["countdown"],
                       cd_accent=q["cd_accent"], bar_accent=q["bar_accent"],
                       outdir=f"{FRAMES}/q{q['idx']}")
            R.render_question(cfg)
        # frame 0 (full timer + full bar) doubles as the static "read" plate
        shutil.copy(f"{FRAMES}/q{q['idx']}/00000.png", f"{FRAMES}/q{q['idx']}_read.png")

        if q["kind"] == "arrow":
            R.render_arrow_reveal(f"{FRAMES}/r{q['idx']}.png", R.MINT, q["ans"],
                                  q["ans_dir"], q["ans_label"], q["expl"])
        else:
            R.render_reveal(f"{FRAMES}/r{q['idx']}.png", R.MINT, q["ans"],
                            q["ans_label"], q["expl"])

    R.render_score(f"{FRAMES}/score.png", tiers=SCORE_TIERS)
    R.render_outro(f"{FRAMES}/outro.png")
    print(f"frames: title + {TOTAL_Q} questions (+countdowns) + reveals + score + outro -> {FRAMES}")


# ------------------------------------------------------------------- bodies
def bodies():
    os.makedirs(BODIES, exist_ok=True)
    for key, (style, line) in NARR.items():
        body = {"model": MODEL, "input": f"{style}: {line}", "voice": VOICE}
        with open(f"{BODIES}/{key}.json", "w") as f:
            json.dump(body, f)
    print(f"bodies: wrote {len(NARR)} Gemini TTS request bodies -> {BODIES}")


# -------------------------------------------------------------- clip helpers
def _static_clip(out, png, vo_key, ding=False):
    d = round(LEAD + wav_dur(f"{VO}/{vo_key}.wav") + TRAIL, 3)
    dly = int(LEAD * 1000)
    cmd = [FF, "-y", "-loglevel", "error",
           "-loop", "1", "-framerate", "30", "-t", f"{d}", "-i", png,
           "-i", f"{VO}/{vo_key}.wav"]
    if ding:
        cmd += ["-f", "lavfi", "-i", f"aevalsrc=exprs='{DING}':d=2:s={AR}"]
        fc = (f"[1:a]adelay={dly}|{dly}[vo];"
              f"[2:a]adelay=120|120[dg];"
              f"[vo][dg]amix=inputs=2:normalize=0,apad[a]")
    else:
        fc = f"[1:a]adelay={dly}|{dly},apad[a]"
    cmd += ["-filter_complex", fc, "-map", "0:v", "-map", "[a]",
            *ENC_INT, *AENC, "-t", f"{d}", out]
    sh(cmd)
    return d


def _count_clip(out, qidx, cd):
    seg = f"{FRAMES}/q{qidx}"
    n = len([x for x in os.listdir(seg) if x.endswith(".png")])
    base = round(n / 30.0, 3)                       # cd + 1s hold on "0"
    tu = wav_dur(f"{VO}/timesup.wav")
    tu_at = float(cd)                               # fire "time's up" as clock hits 0
    d = round(max(base, tu_at + tu + 0.30), 3)      # hold last frame so VO rings out
    hold = round(d - base, 3)
    vf = "[0:v]tpad=stop_mode=clone:stop_duration=%s[v]" % hold if hold > 0 else None
    dly = int(tu_at * 1000)
    af = (f"[2:a]adelay={dly}|{dly}[tu];"
          f"[1:a][tu]amix=inputs=2:normalize=0,apad[a]")
    fc = (vf + ";" + af) if vf else af
    vmap = "[v]" if vf else "0:v"
    cmd = [FF, "-y", "-loglevel", "error",
           "-framerate", "30", "-i", f"{seg}/%05d.png",
           "-f", "lavfi", "-i", f"aevalsrc=exprs='{TICK}':d={cd}:s={AR}",  # ticks stop at 0
           "-i", f"{VO}/timesup.wav",
           "-filter_complex", fc,
           "-map", vmap, "-map", "[a]", *ENC_INT, *AENC, "-t", f"{d}", out]
    sh(cmd)
    return d


def _plan():
    """Ordered per-segment timeline: (clip name, kind, arg, vo_key, ding, cd)."""
    seq = [("title", "static", f"{FRAMES}/title.png", "intro", False, None)]
    for q in QUESTIONS:
        i = q["idx"]
        seq.append((f"q{i}read", "static", f"{FRAMES}/q{i}_read.png", f"q{i}", False, None))
        seq.append((f"q{i}cnt", "count", i, None, None, q["countdown"]))
        seq.append((f"r{i}", "static", f"{FRAMES}/r{i}.png", f"r{i}", True, None))
    seq.append(("score", "static", f"{FRAMES}/score.png", "score", False, None))
    seq.append(("outro", "static", f"{FRAMES}/outro.png", "outro", False, None))
    return [(f"{n:02d}_{name}", kind, arg, vo, ding, cd)
            for n, (name, kind, arg, vo, ding, cd) in enumerate(seq, 1)]


def _probe_dur(path):
    return float(sh([FP, "-v", "error", "-show_entries", "format=duration",
                     "-of", "default=nk=1:nw=1", path]).stdout.strip())


# ------------------------------------------------------------------- build
def build():
    os.makedirs(CLIPS, exist_ok=True)
    clips, rows, total = [], [], 0.0
    for name, kind, arg, vo, ding, cd in _plan():
        out = f"{CLIPS}/{name}.mp4"
        d = _static_clip(out, arg, vo, ding=ding) if kind == "static" else _count_clip(out, arg, cd)
        clips.append(out)
        rows.append([name, kind, d])
        total += d
        print(f"  built {name:10s} {kind:6s} {d:6.2f}s")

    # concat -> HQ video + baked VO/SFX audio (single crf16/slow compression pass)
    ins = []
    for c in clips:
        ins += ["-i", c]
    streams = "".join(f"[{i}:v][{i}:a]" for i in range(len(clips)))
    fc = f"{streams}concat=n={len(clips)}:v=1:a=1[v][a]"
    sh([FF, "-y", "-loglevel", "error", *ins, "-filter_complex", fc,
        "-map", "[v]", "-map", "[a]", *ENC_HQ, *AENC, "-movflags", "+faststart",
        CONCAT_AV])

    with open(META, "w") as f:
        json.dump({"rows": rows, "total": total}, f)
    print(f"\nSegments: {len(rows)}   target total ~{total:.2f}s")
    print("A/V master (HQ video + VO):", CONCAT_AV)


# ------------------------------------------------------------------- music
def _build_bed(total, gain_db):
    """Fanfare open -> looped Prize Wheel Parade bed -> Winner Spin close, with
    crossfades and fade in/out, summed and trimmed to `total`, at master gain."""
    bed = f"{WORK}/bed.wav"
    par_start = FAN_LEN - XF
    win_start = max(par_start + 6.0, total - WIN_LEN)
    par_len = max(4.0, (win_start + XF) - par_start)
    fan_delay = 0
    par_delay = int(par_start * 1000)
    win_delay = int(win_start * 1000)

    def stem(idx, dur, vol, delay_ms):
        fo = max(0.1, dur - FADE)
        s = (f"[{idx}:a]atrim=0:{dur:.3f},asetpts=PTS-STARTPTS,"
             f"afade=t=in:st=0:d={FADE},afade=t=out:st={fo:.3f}:d={FADE},"
             f"volume={vol:.2f}dB,aformat=sample_rates={AR}:channel_layouts=stereo")
        if delay_ms:
            s += f",adelay={delay_ms}|{delay_ms}"
        return s

    fc = (
        stem(0, FAN_LEN, STEM_VOL["fan"], fan_delay) + "[a];"
        + stem(1, par_len, STEM_VOL["par"], par_delay) + "[b];"
        + stem(2, WIN_LEN, STEM_VOL["win"], win_delay) + "[c];"
        f"[a][b][c]amix=inputs=3:normalize=0:dropout_transition=0,"
        f"atrim=0:{total:.3f},asetpts=PTS-STARTPTS,volume={gain_db:.2f}dB,"
        f"aresample={AR}[bed]"
    )
    sh([FF, "-y", "-loglevel", "error",
        "-i", FANFARE, "-stream_loop", "-1", "-i", PARADE, "-i", WINNER,
        "-filter_complex", fc, "-map", "[bed]", "-ac", "2", "-ar", str(AR), bed])
    return bed, dict(par_start=par_start, win_start=win_start, par_len=par_len)


def _duck(bed, vo):
    """Sidechain-compress the music bed, keyed by the VO, so music ducks when the
    host speaks and swells back in the gaps."""
    ducked = f"{WORK}/bed_ducked.wav"
    sh([FF, "-y", "-loglevel", "error", "-i", bed, "-i", vo,
        "-filter_complex", f"[0:a][1:a]sidechaincompress={SC}[out]",
        "-map", "[out]", "-ac", "2", "-ar", str(AR), ducked])
    return ducked


def _mean_db(path, t0, t1):
    """Mean volume (dBFS) of a time window via ffmpeg volumedetect."""
    p = subprocess.run([FF, "-hide_banner", "-nostats", "-ss", f"{t0:.3f}",
                        "-to", f"{t1:.3f}", "-i", path, "-af", "volumedetect",
                        "-f", "null", "-"], capture_output=True, text=True)
    m = re.search(r"mean_volume:\s*(-?[\d.]+) dB", p.stderr)
    return float(m.group(1)) if m else float("nan")


def music():
    meta = json.load(open(META))
    rows, total = meta["rows"], meta["total"]
    total = _probe_dur(CONCAT_AV)  # authoritative

    # extract the VO/SFX master audio (sidechain key + top layer)
    vo = f"{WORK}/vo.wav"
    sh([FF, "-y", "-loglevel", "error", "-i", CONCAT_AV, "-vn",
        "-acodec", "pcm_s16le", "-ar", str(AR), "-ac", "2", vo])

    # measurement windows from the title/intro segment
    title_dur = rows[0][2]
    intro_vo = wav_dur(f"{VO}/intro.wav")
    sp0, sp1 = LEAD + 0.5, LEAD + intro_vo - 0.5          # VO speech window
    mo0, mo1 = title_dur - 0.55, title_dur - 0.10          # music-only (VO silent) window
    vo_mean = _mean_db(vo, sp0, sp1)

    # pass 1: neutral master gain -> measure the natural VO/music separation
    bed0, _ = _build_bed(total, 0.0)
    duck0 = _duck(bed0, vo)
    m_under0 = _mean_db(duck0, sp0, sp1)
    sep0 = vo_mean - m_under0
    gain = round(sep0 - TARGET_SEP_DB, 2)                  # slope is -1 dB/dB

    # pass 2: calibrated bed -> duck -> mux
    bed, cues = _build_bed(total, gain)
    ducked = _duck(bed, vo)
    sh([FF, "-y", "-loglevel", "error", "-i", CONCAT_AV, "-i", ducked,
        "-filter_complex",
        "[0:a][1:a]amix=inputs=2:normalize=0:duration=first,alimiter=limit=0.98:level=false[a]",
        "-map", "0:v", "-map", "[a]", "-c:v", "copy", *AENC,
        "-movflags", "+faststart", OUT])

    # final measurements
    m_under = _mean_db(ducked, sp0, sp1)      # ducked music under VO
    m_only = _mean_db(ducked, mo0, mo1)       # music bed with VO silent (full)
    out_sp = _mean_db(OUT, sp0, sp1)          # final mix during VO
    out_mo = _mean_db(OUT, mo0, mo1)          # final mix, music-only
    sep = vo_mean - m_under
    duck_depth = m_only - m_under

    print("\n=== MUSIC / LOUDNESS ===")
    print(f"  master bed gain (auto-calibrated): {gain:+.2f} dB  (pass-1 sep {sep0:.1f} dB)")
    print(f"  cues: fanfare 0-{FAN_LEN:.0f}s | parade {cues['par_start']:.1f}-"
          f"{cues['win_start']:.1f}s (looped, {cues['par_len']:.0f}s) | "
          f"winner {cues['win_start']:.1f}-{total:.1f}s")
    print(f"  VO speech window   [{sp0:.2f},{sp1:.2f}]s  mean {vo_mean:.1f} dBFS")
    print(f"  music UNDER VO     mean {m_under:.1f} dBFS   -> VO is {sep:.1f} dB above music")
    print(f"  music-only (gap)   mean {m_only:.1f} dBFS   -> sidechain duck depth {duck_depth:.1f} dB")
    print(f"  final mix @VO      mean {out_sp:.1f} dBFS")
    print(f"  final mix @gap     mean {out_mo:.1f} dBFS")

    _verify(rows, total)


def _verify(rows, total):
    print("\n=== FFPROBE VERIFY ===")
    info = sh([FP, "-v", "error", "-show_entries",
               "format=duration,size:stream=codec_type,codec_name,width,height,"
               "r_frame_rate,sample_rate,channels,duration",
               "-of", "default=noprint_wrappers=1", OUT]).stdout
    print(info.strip())
    # A/V sync: compare stream durations
    vdur = _probe_dur_stream("v")
    adur = _probe_dur_stream("a")
    print(f"  video {vdur:.3f}s  audio {adur:.3f}s  drift {abs(vdur-adur)*1000:.0f} ms")

    # extract 3 representative frames from the FINAL mp4
    off, cur = {}, 0.0
    for name, _kind, d in rows:
        off[name] = cur
        cur += d
    grab = [
        ("verbal-Q1", off["02_q1read"] + 1.2, "/tmp/round02_frame_verbal.png"),
        ("arrow-Q5", off["14_q5read"] + 1.0, "/tmp/round02_frame_arrow.png"),
        ("outro", off["18_outro"] + min(2.5, rows[-1][2] - 0.5), "/tmp/round02_frame_outro.png"),
    ]
    print("\n=== SAMPLE FRAMES ===")
    for label, t, path in grab:
        sh([FF, "-y", "-loglevel", "error", "-ss", f"{t:.3f}", "-i", OUT,
            "-frames:v", "1", path])
        print(f"  {label:10s} @ {t:6.2f}s -> {path}")
    print(f"\nOUTPUT: {OUT}")


def _probe_dur_stream(kind):
    return float(sh([FP, "-v", "error", "-select_streams", f"{kind}:0",
                     "-show_entries", "stream=duration", "-of",
                     "default=nk=1:nw=1", OUT]).stdout.strip())


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "build"
    {"frames": frames, "bodies": bodies, "build": build, "music": music}[cmd]()
