#!/usr/bin/env python3
"""
Render the Gemini-voiced master quiz video -- Round 05, "CogAT Style".

Reuses the established Round-01/02 pipeline verbatim (imports the shared brand
module render_demo_quiz.py READ-ONLY -- it is never modified):
  - on-brand Pillow plates (Anton + DM Sans, thick black borders, hard ZERO-blur
    offset shadows, rotating color blocks, mint checks), supersampled AA (QUIZ_SS),
  - narration generated by Gemini TTS (gemini-2.5-pro-preview-tts, voice "Puck")
    via the TrueFoundry gateway (see gen_vo.sh; API key never printed),
  - a light tick bed under each countdown + a soft ding under each reveal,
  - a ducked music arc (Game Show Fanfare -> Prize Wheel Parade bed -> Winner
    Spin) sidechained under the VO, then an HQ libx264 crf16/slow encode.

Content is the 5 ORIGINAL CogAT-STYLE reasoning items in
video/content/cogat-style-round-05.md:
  Q1 verbal analogy (GIANT:TINY :: WIDE:?)          -> A) NARROW
  Q2 verbal classification / odd-one-out            -> D) NUMBER
  Q3 number series (100 92 84 76 ?)                 -> B) 68
  Q4 number analogy (n -> n^3)                      -> B) 125
  Q5 NONVERBAL figure-series / POSITION             -> B) BOTTOM-LEFT
     (a dot stepping clockwise around a square's corners, drawn as icons).
Parent-email gate only; no child PII; no Alpha branding.

The Round-05 nonverbal item is a *dot-position* puzzle (not the Round-02 arrow
rotation), so its drawing helpers (draw_dot_square / dot_option_tile /
render_dot_question / render_dot_reveal) live HERE in this file and only call the
shared module's PUBLIC helpers -- the shared render_demo_quiz.py stays untouched.

Steps (run in order):
  render_cogat_round_05.py frames   # draw all PNGs / countdown sequences (SSAA)
  render_cogat_round_05.py bodies   # write Gemini TTS request bodies (no API key)
  # ...then generate the wavs:
  #   set -a; . .env.local; set +a
  #   VO_BODIES=/tmp/vo_r05/bodies VO_OUT=/tmp/vo_r05 bash video/tools/gen_vo.sh
  render_cogat_round_05.py build    # size to VO, per-seg HQ clips, concat -> A/V master
  render_cogat_round_05.py music    # ducked music bed, mux, verify, sample frames
"""
import contextlib
import json
import os
import re
import shutil
import subprocess
import sys
import wave

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
os.environ.setdefault("QUIZ_SS", "4")  # crisp supersampled anti-aliasing
import render_demo_quiz as R  # noqa: E402  (brand plate drawing + palette; READ-ONLY)

FF = "/opt/homebrew/bin/ffmpeg"
FP = "/opt/homebrew/bin/ffprobe"
ROOT = "/Users/khoilam/Documents/Crossover/30mpc-website-design-cursor"

# --- Round-05 private scratch space (collision-free vs sibling round workers) ---
WORK = "/tmp/r05_work"
FRAMES = f"{WORK}/frames"
CLIPS = f"{WORK}/clips"
VO = "/tmp/vo_r05"
BODIES = f"{VO}/bodies"
META = f"{WORK}/meta.json"
CONCAT_AV = f"{WORK}/round-05-concat.mp4"   # HQ video + VO/SFX audio
OUT = f"{ROOT}/video/renders/round-05-cogat-master.mp4"

# The user's music assets -- read IN PLACE, never moved/altered.
MUSIC_DIR = "/Users/khoilam/Documents/Crossover/Smart Fella Video Campaign/Audio Assets/Music"
FANFARE = f"{MUSIC_DIR}/Game Show Fanfare.mp3"
PARADE = f"{MUSIC_DIR}/Prize Wheel Parade (1).mp3"
WINNER = f"{MUSIC_DIR}/Winner Spin.mp3"

MODEL = "gemini-2.5-pro-preview-tts"
VOICE = "Puck"  # upbeat Gemini prebuilt voice -> game-show host energy

# Natural-language style directives. Gemini TTS interprets (does NOT speak) the
# text before the colon (verified in Round 01: prefixed vs plain = same spoken
# length, different prosody).
HOST = "Read this like a high-energy, upbeat TV game-show host, fast and punchy"
REVEAL = "Read this like a game-show host cheerfully revealing the answer"
URGENT = "Shout this with urgent, excited game-show energy"
WARM = "Read this warmly and invitingly, like a friendly game-show host"

# key -> (style, spoken line). Fresh, ORIGINAL Round-05 narration (not reused).
NARR = {
    "intro": (HOST,
              "Welcome back to the Brain Teaser Quiz, and welcome to Round five! "
              "We've got five fresh brain-benders lined up: word puzzles, number "
              "patterns, and one sneaky picture challenge. Fingers on the buzzers, "
              "eyes on the clock... let's play!"),
    "q1": (HOST,
           "Question one, a word analogy. Giant is to tiny, as wide is to... "
           "what? Your choices: A, narrow... B, tall... C, long... or D, big. "
           "Five seconds, go!"),
    "q2": (HOST,
           "Question two, spot the odd one out! Add, subtract, multiply, number. "
           "Three of these are things you do, and one is not. Which one does not "
           "belong, A, B, C, or D? Six seconds!"),
    "q3": (HOST,
           "Question three, a number series. One hundred, ninety-two, eighty-four, "
           "seventy-six, and then... what? A, seventy... B, sixty-eight... C, "
           "sixty-six... or D, seventy-two? Six seconds on the clock!"),
    "q4": (HOST,
           "Question four, and this one is tricky! Two makes eight, three makes "
           "twenty-seven, four makes sixty-four, so five makes... what? A, one "
           "hundred... B, one hundred twenty-five... C, eighty-one... or D, two "
           "hundred sixteen? Eight seconds, take your time!"),
    "q5": (HOST,
           "Last one, a picture puzzle! Watch the dot travel around the square, "
           "clockwise: top-left, top-right, bottom-right... where does it jump "
           "next? A, top-left... B, bottom-left... C, top-right... or D, the "
           "center? Seven seconds!"),
    "timesup": (URGENT, "And that's time! Pencils down!"),
    "r1": (REVEAL,
           "The answer is A, narrow! Giant and tiny are opposites, so the "
           "opposite of wide has to be narrow!"),
    "r2": (REVEAL,
           "It's D, number! Add, subtract, and multiply are all things you do. "
           "But a number? That's the thing you do them to!"),
    "r3": (REVEAL,
           "The answer is B, sixty-eight! Each step drops by eight: one hundred, "
           "ninety-two, eighty-four, seventy-six... and eight less than "
           "seventy-six is sixty-eight!"),
    "r4": (REVEAL,
           "It's B, one hundred twenty-five! Every number is cubed, multiplied by "
           "itself three times. Two cubed is eight, three cubed is twenty-seven, "
           "and five cubed is one hundred twenty-five!"),
    "r5": (REVEAL,
           "The answer is B, bottom-left! The dot steps clockwise from corner to "
           "corner: top-left, top-right, bottom-right... and the very next corner "
           "is bottom-left!"),
    "score": (HOST,
              "So, how did you score? Five out of five, take a bow, you're a "
              "certified smart fella! Three or four, you're one sharp cookie! "
              "Two or fewer? Don't sweat it, every champion starts out a rookie "
              "riddler!"),
    "outro": (WARM,
              "Want to see your full results and how you stack up? Ask a parent "
              "or guardian to type their email on the screen. There are five "
              "hundred dollar and two thousand dollar prizes up for grabs for "
              "parents. Check the official rules, and we'll see you next round!"),
}

# ---- the 5 CogAT-style questions (see video/content/cogat-style-round-05.md) ----
TOTAL_Q = 5
QUESTIONS = [
    dict(idx=1, kind="text", bg=R.BLUE, tier="VERBAL ANALOGY", tier_color=R.MINT,
         question="GIANT IS TO TINY AS\nWIDE IS TO ?",
         options=[("A", "NARROW"), ("B", "TALL"), ("C", "LONG"), ("D", "BIG")],
         countdown=5, cd_accent=R.YELLOW, bar_accent=R.YELLOW,
         ans="A", ans_label="NARROW",
         expl="Giant and tiny are opposites, so the opposite of wide is narrow - "
              "the same relationship, flipped."),
    dict(idx=2, kind="text", bg=R.CORAL, tier="ODD ONE OUT", tier_color=R.MINT,
         question="WHICH ONE DOES NOT BELONG?",
         options=[("A", "ADD"), ("B", "SUBTRACT"), ("C", "MULTIPLY"), ("D", "NUMBER")],
         countdown=6, cd_accent=R.YELLOW, bar_accent=R.YELLOW,
         ans="D", ans_label="NUMBER",
         expl="Add, subtract, and multiply are operations you do. A number is the "
              "thing you do them to, so it doesn't belong."),
    dict(idx=3, kind="text", bg=R.YELLOW, tier="NUMBER SERIES", tier_color=R.CORAL,
         question="WHAT COMES NEXT?\n100   92   84   76   ?",
         options=[("A", "70"), ("B", "68"), ("C", "66"), ("D", "72")],
         countdown=6, cd_accent=R.CORAL, bar_accent=R.CORAL,
         ans="B", ans_label="68",
         expl="Each number goes down by 8: 100, 92, 84, 76, so 76 - 8 = 68."),
    dict(idx=4, kind="text", bg=R.BLUE, tier="NUMBER ANALOGY", tier_color=R.YELLOW,
         question="WHICH NUMBER FITS?\n2 -> 8,   3 -> 27,   4 -> 64,   5 -> ?",
         options=[("A", "100"), ("B", "125"), ("C", "81"), ("D", "216")],
         countdown=8, cd_accent=R.YELLOW, bar_accent=R.YELLOW,
         ans="B", ans_label="125",
         expl="Each number is cubed (n x n x n): 2 cubed is 8, 3 cubed is 27, "
              "4 cubed is 64, so 5 cubed is 125."),
    dict(idx=5, kind="dot", bg=R.CORAL, tier="POSITION", tier_color=R.YELLOW,
         prompt="WHERE DOES THE DOT MOVE NEXT?",
         seq=["tl", "tr", "br"],
         options=[("A", "tl"), ("B", "bl"), ("C", "tr"), ("D", "center")],
         countdown=7, cd_accent=R.YELLOW, bar_accent=R.YELLOW,
         ans="B", ans_label="BOTTOM-LEFT", ans_pos="bl",
         expl="The dot steps clockwise corner to corner: top-left, top-right, "
              "bottom-right, then the next corner is bottom-left."),
]

SCORE_TIERS = [
    ("5 / 5", "CERTIFIED SMART FELLA", R.MINT),
    ("3-4", "SHARP COOKIE", R.YELLOW),
    ("0-2", "ROOKIE RIDDLER", R.CORAL),
]

# Light audio bed exprs (kept low so the VO stays on top).
TICK = "0.09*sin(2*PI*1150*t)*exp(-32*mod(t,1))"
DING = "0.16*sin(2*PI*880*t)*exp(-3.5*t)+0.10*sin(2*PI*1320*t)*exp(-3.5*t)"

LEAD = 0.35      # silence before VO on static plates
TRAIL = 0.80     # silence after VO on static plates
AR = 48000

# --- HQ deliverable encode (user spec: libx264 crf16 preset slow, yuv420p) ---
ENC_HQ = [
    "-c:v", "libx264", "-preset", "slow", "-crf", "16", "-pix_fmt", "yuv420p",
    "-r", "30", "-profile:v", "high", "-level:v", "4.2",
    "-x264-params", "keyint=60:min-keyint=60:scenecut=0",
    "-color_primaries", "bt709", "-color_trc", "bt709", "-colorspace", "bt709",
]
# Near-lossless per-segment intermediate so the single crf16 concat is the only
# meaningful compression step (no visible generation loss on the flat-color art).
ENC_INT = [
    "-c:v", "libx264", "-preset", "veryfast", "-crf", "12", "-pix_fmt", "yuv420p",
    "-r", "30", "-profile:v", "high", "-level:v", "4.2",
    "-x264-params", "keyint=60:min-keyint=60:scenecut=0",
    "-color_primaries", "bt709", "-color_trc", "bt709", "-colorspace", "bt709",
]
AENC = ["-c:a", "aac", "-b:a", "192k", "-ar", str(AR), "-ac", "2"]

# --- music mix design (same ducked arc as Round 01/02) ---
FADE = 1.5
XF = 1.5                 # fanfare->parade overlap
FAN_LEN = 13.0          # fanfare open length
WIN_LEN = 15.0          # winner-spin close length
STEM_VOL = {"fan": 0.0, "par": -2.5, "win": -1.0}  # parade bed sits lowest
# sidechain duck: music is compressed whenever the VO (sidechain key) is present
SC = "threshold=0.03:ratio=8:attack=20:release=320:makeup=1:detection=rms:link=average"
TARGET_SEP_DB = 12.0    # aim: music ~12 dB under the VO during narration (10-14 band)


# ===================================================================
#  Round-05 NONVERBAL "dot position" drawing helpers (LOCAL to this file).
#  They only call render_demo_quiz PUBLIC helpers; they never modify it.
# ===================================================================
POS_LABEL = {"tl": "TOP-LEFT", "tr": "TOP-RIGHT", "br": "BOTTOM-RIGHT",
             "bl": "BOTTOM-LEFT", "center": "CENTER"}


def draw_dot_square(d, box, position, dot_col=R.CORAL, sq_fill=R.PAPER,
                    border=7, shadow=11, sq_radius=10, ghost=True):
    """Neo-brutalist POSITION icon: a bordered square with a colored dot at one of
    its four corners (or dead center). Faint 'ghost' pips mark the other corners
    so the moving-dot geometry reads at a glance. Drawn in logical 1920x1080 units;
    the shared _SSDraw wrapper supersamples it so circle + border edges stay crisp.
    position may be None to draw an empty square (used for the '?' cell)."""
    x0, y0, x1, y1 = box
    if shadow:  # hard ZERO-blur offset shadow
        d.rounded_rectangle([x0 + shadow, y0 + shadow, x1 + shadow, y1 + shadow],
                            radius=sq_radius, fill=R.INK)
    d.rounded_rectangle([x0, y0, x1, y1], radius=sq_radius, fill=sq_fill)
    d.rounded_rectangle([x0, y0, x1, y1], radius=sq_radius, outline=R.INK, width=border)

    side = min(x1 - x0, y1 - y0)
    pad = side * 0.22
    dr = side * 0.14
    pos = {
        "tl": (x0 + pad, y0 + pad), "tr": (x1 - pad, y0 + pad),
        "br": (x1 - pad, y1 - pad), "bl": (x0 + pad, y1 - pad),
        "center": ((x0 + x1) / 2, (y0 + y1) / 2),
    }
    if ghost:  # faint pips at the four corners -> "corners of a square"
        g = dr * 0.34
        for k in ("tl", "tr", "br", "bl"):
            gx, gy = pos[k]
            d.ellipse([gx - g, gy - g, gx + g, gy + g], fill=(176, 176, 176))
    if position:
        cx, cy = pos[position]
        ds = max(4, dr * 0.18)
        d.ellipse([cx - dr + ds, cy - dr + ds, cx + dr + ds, cy + dr + ds], fill=R.INK)
        d.ellipse([cx - dr, cy - dr, cx + dr, cy + dr], fill=dot_col)
        d.ellipse([cx - dr, cy - dr, cx + dr, cy + dr], outline=R.INK,
                  width=max(4, border - 1))


def dot_option_tile(d, box, letter, position, highlight=None):
    """An A-D option tile whose choice is a dot-POSITION icon (not text): a letter
    badge, a small square with the dot at that position, and a short caption."""
    fill = R.MINT if highlight == "correct" else R.PAPER
    R.hard_card(d, box, fill, radius=26, border=7, shadow=12)
    x0, y0, x1, y1 = box
    bsz = 74
    bx0, by0 = x0 + 22, y0 + 20
    R.hard_card(d, [bx0, by0, bx0 + bsz, by0 + bsz], R.BADGE_COLORS[letter],
                radius=16, border=6, shadow=7)
    R.draw_text(d, bx0 + bsz / 2, by0 + bsz / 2, letter, R.anton(int(bsz * 0.58)),
                R.INK, anchor="mm")
    isz = 116
    icx = (x0 + x1) / 2
    itop = y0 + 26
    draw_dot_square(d, [icx - isz / 2, itop, icx + isz / 2, itop + isz], position,
                    dot_col=R.BADGE_COLORS[letter], border=6, shadow=8, sq_radius=8)
    R.draw_text(d, icx, itop + isz + 30, POS_LABEL[position], R.dm(28, "Bold"),
                R.INK, anchor="mm", tracking=1)


def render_dot_question(cfg):
    """Nonverbal figure-series / POSITION item (CogAT style): a dot stepping
    clockwise around a square's corners (TL -> TR -> BR -> ?), plus four
    dot-position option icons. Rebuilds the exact brand chrome + countdown of the
    shared render_arrow_question WITHOUT editing the shared module -- it only calls
    render_demo_quiz's public helpers.

    cfg keys: idx, total, bg, tier, tier_color, prompt, seq(list of positions),
    options(list of (letter, position)), countdown, cd_accent, bar_accent, outdir.
    """
    outdir = cfg["outdir"]
    if os.path.isdir(outdir):
        shutil.rmtree(outdir)
    os.makedirs(outdir)

    base, d = R.new_frame(cfg["bg"])

    total = cfg.get("total", TOTAL_Q)
    r = R.pill_left(d, R.M, 100, f"QUESTION {cfg['idx']} OF {total}",
                    R.dm(34, "Bold"), fill=R.INK, txt_col=R.PAPER, tracking=3)
    tier_col = cfg.get("tier_color") or R.YELLOW
    R.pill_left(d, r + 24, 100, cfg["tier"].upper(), R.dm(34, "Bold"),
                tier_col, txt_col=R.INK, tracking=3)

    R.hard_card(d, [R.CD_X0, R.CD_Y0, R.CD_X1, R.CD_Y1], cfg["cd_accent"],
                radius=28, border=9, shadow=14)

    # prompt card (same geometry as the shared render_arrow_question)
    pbox = [R.M, 250, R.W - R.M, 396]
    R.hard_card(d, pbox, R.PAPER, radius=36, border=9, shadow=16)
    pf, plines = R.fit_font(d, cfg["prompt"], pbox[2] - pbox[0] - 90,
                            pbox[3] - pbox[1] - 28, [64, 58, 52, 46])
    R.draw_multiline_center(d, R.W / 2, (pbox[1] + pbox[3]) / 2, plines, pf, R.INK)

    # sequence strip: known dot-positions + a "?" cell
    seq = cfg["seq"]
    n = len(seq) + 1
    cw, chh, gap = 190, 190, 70
    sx = (R.W - (n * cw + (n - 1) * gap)) / 2
    sy = 430
    seq_colors = [R.BLUE, R.CORAL, R.YELLOW, R.MINT]
    for i, posn in enumerate(seq):
        bx = sx + i * (cw + gap)
        draw_dot_square(d, [bx, sy, bx + cw, sy + chh], posn,
                        dot_col=seq_colors[i % len(seq_colors)])
    # the missing "?" cell (empty square + ghost pips + big question mark)
    bx = sx + len(seq) * (cw + gap)
    draw_dot_square(d, [bx, sy, bx + cw, sy + chh], None)
    R.draw_text(d, bx + cw / 2, sy + chh / 2, "?", R.anton(int(chh * 0.50)),
                R.INK, anchor="mm")

    # option row: four dot-position icon tiles
    ow, oh, ogap = 395, 240, 40
    oy = 662
    for j, (letter, posn) in enumerate(cfg["options"]):
        bx = R.M + j * (ow + ogap)
        dot_option_tile(d, [bx, oy, bx + ow, oy + oh], letter, posn)

    # bar track (solid black; accent fill drawn per-frame by _countdown_sequence)
    d.rounded_rectangle([R.BAR_X, R.BAR_Y, R.BAR_X + R.BAR_W, R.BAR_Y + R.BAR_H],
                        radius=R.BAR_H // 2, fill=R.INK)

    return R._countdown_sequence(base, outdir, cfg["countdown"], cfg["bar_accent"])


def render_dot_reveal(path, bg, letter, position, label, explanation):
    """Reveal plate for the dot-position item: a big dot-square icon showing the
    winning corner + the A-D label + mint check, over render_reveal's card system.
    Mirrors the shared render_arrow_reveal but lives HERE (shared module untouched)."""
    img, d = R.new_frame(bg)
    R.pill_center(d, R.W / 2, 150, "CORRECT ANSWER", R.dm(38, "Bold"),
                  txt_col=R.PAPER, tracking=4, fill=R.INK, pad_x=36, pad_y=18)
    box = [R.M, 250, R.W - R.M, 636]
    R.hard_card(d, box, R.PAPER, radius=44, border=10, shadow=22)
    cy = (box[1] + box[3]) / 2
    isz = 300
    ix0 = R.M + 80
    draw_dot_square(d, [ix0, cy - isz / 2, ix0 + isz, cy + isz / 2], position,
                    dot_col=R.BADGE_COLORS[letter], border=9, shadow=14, sq_radius=14)
    R.badge_circle(d, box[2] - 150, box[1] + 110, 58, R.MINT)
    R.draw_check(d, box[2] - 150, box[1] + 110, 72, R.INK, width=18)
    lab_left = ix0 + isz + 90
    lf, llines = R.fit_font(d, f"{letter})  {label}", (R.W - R.M) - lab_left - 40,
                            220, [116, 104, 92, 80])
    R.draw_multiline_center(d, (lab_left + (R.W - R.M)) / 2, cy, llines, lf, R.INK)
    ebox = [R.M, 686, R.W - R.M, 902]
    R.hard_card(d, ebox, R.CREAM, radius=36, border=8, shadow=16)
    ef = R.dm(40, "Medium")
    elines = R.wrap(d, explanation, ef, ebox[2] - ebox[0] - 120)
    R.draw_multiline_center(d, R.W / 2, (ebox[1] + ebox[3]) / 2, elines, ef, R.INK,
                            leading=1.28)
    R._finalize(img).save(path)


# ------------------------------------------------------------------- utils
def sh(cmd):
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode != 0:
        sys.stderr.write("CMD FAILED: " + " ".join(map(str, cmd)) + "\n" + p.stderr + "\n")
        raise SystemExit(1)
    return p


def wav_dur(path):
    with contextlib.closing(wave.open(path, "rb")) as w:
        return w.getnframes() / float(w.getframerate())


# ------------------------------------------------------------------- frames
def frames():
    for d in (FRAMES, CLIPS):
        os.makedirs(d, exist_ok=True)

    R.render_title(f"{FRAMES}/title.png")

    for q in QUESTIONS:
        if q["kind"] == "dot":
            cfg = dict(idx=q["idx"], total=TOTAL_Q, bg=q["bg"], tier=q["tier"],
                       tier_color=q["tier_color"], prompt=q["prompt"], seq=q["seq"],
                       options=q["options"], countdown=q["countdown"],
                       cd_accent=q["cd_accent"], bar_accent=q["bar_accent"],
                       outdir=f"{FRAMES}/q{q['idx']}")
            render_dot_question(cfg)
        else:
            cfg = dict(idx=q["idx"], total=TOTAL_Q, bg=q["bg"], tier=q["tier"],
                       tier_color=q["tier_color"], question=q["question"],
                       options=q["options"], countdown=q["countdown"],
                       cd_accent=q["cd_accent"], bar_accent=q["bar_accent"],
                       outdir=f"{FRAMES}/q{q['idx']}")
            R.render_question(cfg)
        # frame 0 (full timer + full bar) doubles as the static "read" plate
        shutil.copy(f"{FRAMES}/q{q['idx']}/00000.png", f"{FRAMES}/q{q['idx']}_read.png")

        if q["kind"] == "dot":
            render_dot_reveal(f"{FRAMES}/r{q['idx']}.png", R.MINT, q["ans"],
                              q["ans_pos"], q["ans_label"], q["expl"])
        else:
            R.render_reveal(f"{FRAMES}/r{q['idx']}.png", R.MINT, q["ans"],
                            q["ans_label"], q["expl"])

    R.render_score(f"{FRAMES}/score.png", tiers=SCORE_TIERS)
    R.render_outro(f"{FRAMES}/outro.png")
    print(f"frames: title + {TOTAL_Q} questions (+countdowns) + reveals + score + outro -> {FRAMES}")


# ------------------------------------------------------------------- bodies
def bodies():
    os.makedirs(BODIES, exist_ok=True)
    for key, (style, line) in NARR.items():
        body = {"model": MODEL, "input": f"{style}: {line}", "voice": VOICE}
        with open(f"{BODIES}/{key}.json", "w") as f:
            json.dump(body, f)
    print(f"bodies: wrote {len(NARR)} Gemini TTS request bodies -> {BODIES}")


# -------------------------------------------------------------- clip helpers
def _static_clip(out, png, vo_key, ding=False):
    d = round(LEAD + wav_dur(f"{VO}/{vo_key}.wav") + TRAIL, 3)
    dly = int(LEAD * 1000)
    cmd = [FF, "-y", "-loglevel", "error",
           "-loop", "1", "-framerate", "30", "-t", f"{d}", "-i", png,
           "-i", f"{VO}/{vo_key}.wav"]
    if ding:
        cmd += ["-f", "lavfi", "-i", f"aevalsrc=exprs='{DING}':d=2:s={AR}"]
        fc = (f"[1:a]adelay={dly}|{dly}[vo];"
              f"[2:a]adelay=120|120[dg];"
              f"[vo][dg]amix=inputs=2:normalize=0,apad[a]")
    else:
        fc = f"[1:a]adelay={dly}|{dly},apad[a]"
    cmd += ["-filter_complex", fc, "-map", "0:v", "-map", "[a]",
            *ENC_INT, *AENC, "-t", f"{d}", out]
    sh(cmd)
    return d


def _count_clip(out, qidx, cd):
    seg = f"{FRAMES}/q{qidx}"
    n = len([x for x in os.listdir(seg) if x.endswith(".png")])
    base = round(n / 30.0, 3)                       # cd + 1s hold on "0"
    tu = wav_dur(f"{VO}/timesup.wav")
    tu_at = float(cd)                               # fire "time's up" as clock hits 0
    d = round(max(base, tu_at + tu + 0.30), 3)      # hold last frame so VO rings out
    hold = round(d - base, 3)
    vf = "[0:v]tpad=stop_mode=clone:stop_duration=%s[v]" % hold if hold > 0 else None
    dly = int(tu_at * 1000)
    af = (f"[2:a]adelay={dly}|{dly}[tu];"
          f"[1:a][tu]amix=inputs=2:normalize=0,apad[a]")
    fc = (vf + ";" + af) if vf else af
    vmap = "[v]" if vf else "0:v"
    cmd = [FF, "-y", "-loglevel", "error",
           "-framerate", "30", "-i", f"{seg}/%05d.png",
           "-f", "lavfi", "-i", f"aevalsrc=exprs='{TICK}':d={cd}:s={AR}",  # ticks stop at 0
           "-i", f"{VO}/timesup.wav",
           "-filter_complex", fc,
           "-map", vmap, "-map", "[a]", *ENC_INT, *AENC, "-t", f"{d}", out]
    sh(cmd)
    return d


def _plan():
    """Ordered per-segment timeline: (clip name, kind, arg, vo_key, ding, cd)."""
    seq = [("title", "static", f"{FRAMES}/title.png", "intro", False, None)]
    for q in QUESTIONS:
        i = q["idx"]
        seq.append((f"q{i}read", "static", f"{FRAMES}/q{i}_read.png", f"q{i}", False, None))
        seq.append((f"q{i}cnt", "count", i, None, None, q["countdown"]))
        seq.append((f"r{i}", "static", f"{FRAMES}/r{i}.png", f"r{i}", True, None))
    seq.append(("score", "static", f"{FRAMES}/score.png", "score", False, None))
    seq.append(("outro", "static", f"{FRAMES}/outro.png", "outro", False, None))
    return [(f"{n:02d}_{name}", kind, arg, vo, ding, cd)
            for n, (name, kind, arg, vo, ding, cd) in enumerate(seq, 1)]


def _probe_dur(path):
    return float(sh([FP, "-v", "error", "-show_entries", "format=duration",
                     "-of", "default=nk=1:nw=1", path]).stdout.strip())


# ------------------------------------------------------------------- build
def build():
    os.makedirs(CLIPS, exist_ok=True)
    clips, rows, total = [], [], 0.0
    for name, kind, arg, vo, ding, cd in _plan():
        out = f"{CLIPS}/{name}.mp4"
        d = _static_clip(out, arg, vo, ding=ding) if kind == "static" else _count_clip(out, arg, cd)
        clips.append(out)
        rows.append([name, kind, d])
        total += d
        print(f"  built {name:10s} {kind:6s} {d:6.2f}s")

    # concat -> HQ video + baked VO/SFX audio (single crf16/slow compression pass)
    ins = []
    for c in clips:
        ins += ["-i", c]
    streams = "".join(f"[{i}:v][{i}:a]" for i in range(len(clips)))
    fc = f"{streams}concat=n={len(clips)}:v=1:a=1[v][a]"
    sh([FF, "-y", "-loglevel", "error", *ins, "-filter_complex", fc,
        "-map", "[v]", "-map", "[a]", *ENC_HQ, *AENC, "-movflags", "+faststart",
        CONCAT_AV])

    with open(META, "w") as f:
        json.dump({"rows": rows, "total": total}, f)
    print(f"\nSegments: {len(rows)}   target total ~{total:.2f}s")
    print("A/V master (HQ video + VO):", CONCAT_AV)


# ------------------------------------------------------------------- music
def _build_bed(total, gain_db):
    """Fanfare open -> looped Prize Wheel Parade bed -> Winner Spin close, with
    crossfades and fade in/out, summed and trimmed to `total`, at master gain."""
    bed = f"{WORK}/bed.wav"
    par_start = FAN_LEN - XF
    win_start = max(par_start + 6.0, total - WIN_LEN)
    par_len = max(4.0, (win_start + XF) - par_start)
    fan_delay = 0
    par_delay = int(par_start * 1000)
    win_delay = int(win_start * 1000)

    def stem(idx, dur, vol, delay_ms):
        fo = max(0.1, dur - FADE)
        s = (f"[{idx}:a]atrim=0:{dur:.3f},asetpts=PTS-STARTPTS,"
             f"afade=t=in:st=0:d={FADE},afade=t=out:st={fo:.3f}:d={FADE},"
             f"volume={vol:.2f}dB,aformat=sample_rates={AR}:channel_layouts=stereo")
        if delay_ms:
            s += f",adelay={delay_ms}|{delay_ms}"
        return s

    fc = (
        stem(0, FAN_LEN, STEM_VOL["fan"], fan_delay) + "[a];"
        + stem(1, par_len, STEM_VOL["par"], par_delay) + "[b];"
        + stem(2, WIN_LEN, STEM_VOL["win"], win_delay) + "[c];"
        f"[a][b][c]amix=inputs=3:normalize=0:dropout_transition=0,"
        f"atrim=0:{total:.3f},asetpts=PTS-STARTPTS,volume={gain_db:.2f}dB,"
        f"aresample={AR}[bed]"
    )
    sh([FF, "-y", "-loglevel", "error",
        "-i", FANFARE, "-stream_loop", "-1", "-i", PARADE, "-i", WINNER,
        "-filter_complex", fc, "-map", "[bed]", "-ac", "2", "-ar", str(AR), bed])
    return bed, dict(par_start=par_start, win_start=win_start, par_len=par_len)


def _duck(bed, vo):
    """Sidechain-compress the music bed, keyed by the VO, so music ducks when the
    host speaks and swells back in the gaps."""
    ducked = f"{WORK}/bed_ducked.wav"
    sh([FF, "-y", "-loglevel", "error", "-i", bed, "-i", vo,
        "-filter_complex", f"[0:a][1:a]sidechaincompress={SC}[out]",
        "-map", "[out]", "-ac", "2", "-ar", str(AR), ducked])
    return ducked


def _mean_db(path, t0, t1):
    """Mean volume (dBFS) of a time window via ffmpeg volumedetect."""
    p = subprocess.run([FF, "-hide_banner", "-nostats", "-ss", f"{t0:.3f}",
                        "-to", f"{t1:.3f}", "-i", path, "-af", "volumedetect",
                        "-f", "null", "-"], capture_output=True, text=True)
    m = re.search(r"mean_volume:\s*(-?[\d.]+) dB", p.stderr)
    return float(m.group(1)) if m else float("nan")


def music():
    meta = json.load(open(META))
    rows, total = meta["rows"], meta["total"]
    total = _probe_dur(CONCAT_AV)  # authoritative

    # extract the VO/SFX master audio (sidechain key + top layer)
    vo = f"{WORK}/vo.wav"
    sh([FF, "-y", "-loglevel", "error", "-i", CONCAT_AV, "-vn",
        "-acodec", "pcm_s16le", "-ar", str(AR), "-ac", "2", vo])

    # measurement windows from the title/intro segment
    title_dur = rows[0][2]
    intro_vo = wav_dur(f"{VO}/intro.wav")
    sp0, sp1 = LEAD + 0.5, LEAD + intro_vo - 0.5          # VO speech window
    mo0, mo1 = title_dur - 0.55, title_dur - 0.10          # music-only (VO silent) window
    vo_mean = _mean_db(vo, sp0, sp1)

    # pass 1: neutral master gain -> measure the natural VO/music separation
    bed0, _ = _build_bed(total, 0.0)
    duck0 = _duck(bed0, vo)
    m_under0 = _mean_db(duck0, sp0, sp1)
    sep0 = vo_mean - m_under0
    gain = round(sep0 - TARGET_SEP_DB, 2)                  # slope is -1 dB/dB

    # pass 2: calibrated bed -> duck -> mux
    bed, cues = _build_bed(total, gain)
    ducked = _duck(bed, vo)
    sh([FF, "-y", "-loglevel", "error", "-i", CONCAT_AV, "-i", ducked,
        "-filter_complex",
        "[0:a][1:a]amix=inputs=2:normalize=0:duration=first,alimiter=limit=0.98:level=false[a]",
        "-map", "0:v", "-map", "[a]", "-c:v", "copy", *AENC,
        "-movflags", "+faststart", OUT])

    # final measurements
    m_under = _mean_db(ducked, sp0, sp1)      # ducked music under VO
    m_only = _mean_db(ducked, mo0, mo1)       # music bed with VO silent (full)
    out_sp = _mean_db(OUT, sp0, sp1)          # final mix during VO
    out_mo = _mean_db(OUT, mo0, mo1)          # final mix, music-only
    sep = vo_mean - m_under
    duck_depth = m_only - m_under

    print("\n=== MUSIC / LOUDNESS ===")
    print(f"  master bed gain (auto-calibrated): {gain:+.2f} dB  (pass-1 sep {sep0:.1f} dB)")
    print(f"  cues: fanfare 0-{FAN_LEN:.0f}s | parade {cues['par_start']:.1f}-"
          f"{cues['win_start']:.1f}s (looped, {cues['par_len']:.0f}s) | "
          f"winner {cues['win_start']:.1f}-{total:.1f}s")
    print(f"  VO speech window   [{sp0:.2f},{sp1:.2f}]s  mean {vo_mean:.1f} dBFS")
    print(f"  music UNDER VO     mean {m_under:.1f} dBFS   -> VO is {sep:.1f} dB above music")
    print(f"  music-only (gap)   mean {m_only:.1f} dBFS   -> sidechain duck depth {duck_depth:.1f} dB")
    print(f"  final mix @VO      mean {out_sp:.1f} dBFS")
    print(f"  final mix @gap     mean {out_mo:.1f} dBFS")

    _verify(rows, total)


def _verify(rows, total):
    print("\n=== FFPROBE VERIFY ===")
    info = sh([FP, "-v", "error", "-show_entries",
               "format=duration,size:stream=codec_type,codec_name,width,height,"
               "r_frame_rate,sample_rate,channels,duration",
               "-of", "default=noprint_wrappers=1", OUT]).stdout
    print(info.strip())
    # A/V sync: compare stream durations
    vdur = _probe_dur_stream("v")
    adur = _probe_dur_stream("a")
    print(f"  video {vdur:.3f}s  audio {adur:.3f}s  drift {abs(vdur-adur)*1000:.0f} ms")

    # extract the 2 required frames from the FINAL mp4 (a question + the dot item)
    off, cur = {}, 0.0
    for name, _kind, d in rows:
        off[name] = cur
        cur += d
    grab = [
        ("question-Q1", off["02_q1read"] + 1.2, "/tmp/r05_frame_question.png"),
        ("dot-Q5", off["14_q5read"] + 1.0, "/tmp/r05_frame_dot.png"),
    ]
    print("\n=== SAMPLE FRAMES ===")
    for label, t, path in grab:
        sh([FF, "-y", "-loglevel", "error", "-ss", f"{t:.3f}", "-i", OUT,
            "-frames:v", "1", path])
        print(f"  {label:12s} @ {t:6.2f}s -> {path}")
    print(f"\nOUTPUT: {OUT}")


def _probe_dur_stream(kind):
    return float(sh([FP, "-v", "error", "-select_streams", f"{kind}:0",
                     "-show_entries", "stream=duration", "-of",
                     "default=nk=1:nw=1", OUT]).stdout.strip())


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "build"
    {"frames": frames, "bodies": bodies, "build": build, "music": music}[cmd]()
