import { useMemo } from "react";
import { AbsoluteFill, Audio, Sequence, staticFile, useCurrentFrame, useVideoConfig } from "remotion";
import { COLORS } from "../theme/brand";
import { Intro } from "../scenes/Intro";
import { QuestionPlate } from "../scenes/QuestionPlate";
import { QuestionReveal } from "../scenes/QuestionReveal";
import { Score } from "../scenes/Score";
import { Outro } from "../scenes/Outro";
import type { Question } from "../data/types";
import {
  getTimeline,
  type Platform,
  type Segment,
  type TimelineData,
  fanfareBed,
  paradeBed,
  musicLevel,
  winnerVolume,
  winStartFrame,
  GAIN,
} from "./timeline";

/** Countdown-active plate: drives `elapsed` from the sequence-local frame. */
const CountdownPlate: React.FC<{ q: Question }> = ({ q }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  return <QuestionPlate q={q} elapsed={frame / fps} />;
};

const renderSegment = (seg: Segment, platform: Platform): React.ReactNode => {
  switch (seg.type) {
    case "intro":
      return <Intro />;
    case "read":
      return <QuestionPlate q={seg.q} elapsed={0} />;
    case "countdown":
      return <CountdownPlate q={seg.q} />;
    case "reveal":
      return <QuestionReveal q={seg.q} />;
    case "score":
      return <Score />;
    case "outro":
      return <Outro platform={platform} />;
  }
};

const segName = (seg: Segment): string => {
  if (seg.type === "intro" || seg.type === "score" || seg.type === "outro") return seg.type;
  return `Q${seg.q.idx} ${seg.type}`;
};

/**
 * The complete ~11-minute video: every scene sequenced on the shared timeline,
 * with the full existing narration, tick beds, reveal dings, the dynamic
 * fanfare -> parade (looped) -> winner music arc, and burned-in word-by-word
 * captions. `platform` (youtube | instagram | tiktok) selects the outro CTA +
 * outro VO/captions; the whole timeline (and total length) is computed per
 * platform, so an IG/TikTok "follow for more" render is a one-flag switch.
 */
export const FullVideo: React.FC<{ platform?: Platform }> = ({ platform = "youtube" }) => {
  const T: TimelineData = useMemo(() => getTimeline(platform), [platform]);
  const winStart = winStartFrame(T);
  return (
    <AbsoluteFill style={{ backgroundColor: COLORS.ink }}>
      {T.segments.map((seg, i) => (
        <Sequence key={i} from={seg.start} durationInFrames={seg.dur} name={segName(seg)}>
          {renderSegment(seg, platform)}
        </Sequence>
      ))}

      {/* narration */}
      {T.narration.map((a, i) => (
        <Sequence key={`n${i}`} from={a.from} name="VO">
          <Audio src={staticFile(a.src)} />
        </Sequence>
      ))}

      {/* tick beds under each countdown (trimmed to the countdown length) */}
      {T.ticks.map((a, i) => (
        <Sequence key={`t${i}`} from={a.from} durationInFrames={a.durationInFrames} name="ticks">
          <Audio src={staticFile(a.src)} />
        </Sequence>
      ))}

      {/* SFX: per-transition-type whooshes/stings + correct-answer ding at each reveal */}
      {T.sfx.map((a, i) => (
        <Sequence key={`s${i}`} from={a.from} name="sfx">
          <Audio src={staticFile(a.src)} volume={a.vol} />
        </Sequence>
      ))}

      {/* dynamic music arc (duck under VO + swell on countdowns) */}
      <Audio src={staticFile("audio/music/fanfare.mp3")} volume={(f) => musicLevel(f, T) * fanfareBed(f) * GAIN.fanfare} />
      <Audio loop src={staticFile("audio/music/parade.mp3")} volume={(f) => musicLevel(f, T) * paradeBed(f, T) * GAIN.parade} />
      <Sequence from={winStart} name="music · winner">
        <Audio src={staticFile("audio/music/winner.mp3")} volume={(local) => winnerVolume(local, T)} />
      </Sequence>

      {/* No burned-in captions. Subtitles ship only as the .srt/.vtt sidecar
          (full transcript) generated by scripts/gen-subs.ts. The Captions
          component + captions.json remain in the repo, just not rendered. */}
    </AbsoluteFill>
  );
};
